name: 'Nível 3 - Execução por deploy'

on:
  workflow_run:
    workflows: ['Nível 1 - Execução manual']
    types:
      - completed

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install --with-deps

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
